name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_U_KIRCHE_PROD_6CC4C }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Check formatting
        run: npm run format
        working-directory: ./functions

      - name: Deploy to Firebase
        run: firebase deploy --only functions --project u-kirche-prod-6cc4c
